#!/bin/sh
{
echo "start";

echo $HOME;

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

$HOME/.ops/bin/ops image create --package eyberg/redis:5.0.5 -c "$SCRIPT_DIR/../Resources/config.json" -t aws --arch=amd64

$HOME/.ops/bin/ops instance create redis-server-image -p 6379 -c "$SCRIPT_DIR/../Resources/config.json" -t aws

echo "stop";
} 2>&1 | tee -a /tmp/nanos-redis.log
